baseURL = "http://ltv.netlify.com/"
languageCode = "en-us"
title = "Lập trình viên"
enableRobotsTXT = true
enableEmoji = true
theme = "black-and-light"
MetaDataFormat = "yaml"

[params]
  # Enables syntax highlighting
  highlight = true 

  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for what's included in original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim"]

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"
  author = "Hung Nguyen"
  email = "hungneox@gmail.com"
  github = "https://github.com/hungneox/"
  copyrightyear = "2018"

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
  
# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"
